name: Cypress Tests

on:
  # Manual trigger (workflow_dispatch) via GitHub UI
  workflow_dispatch:
  
  # Scheduled trigger (cron job) to run at specific times
  schedule:
    # This will run every day at 00:00 (midnight) UTC
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
    # You can change the cron expression based on your needs. Example:
    # '0 12 * * 1' -> Every Monday at noon (12:00) UTC
  
  # Push event on the main branch
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust Node.js version as necessary

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm ci

      # Step 3: Install Cypress (if not already in package.json)
      - name: Install Cypress
        run: |
          npm install 

      # Step 4: Install Python
      - name: Install Python
        run: |
          sudo apt install python3     

      # Step 5: Run Cypress tests
      - name: Run Cypress Tests
        run: |
          npx cypress run --reporter "junit"

      # Step 6: Install test rail CLI
      - name: Install testrail CLI 
        run: |
          pip install trcli 

      # Step 7: upload results to testrail
      - name: upload results to xml
        run: |
          trcli -y \
            -h "https://gowtham23121991.testrail.io/" \
            -u "gowtham.wc@gmail.com" \
            -p "Gowthn@5" \
            --project_id "2" \
            --suite_id "3" \
            parse_junit \
            -f "test-results.xml" \
            --title "Cypress automated tests - $(date +'%Y-%m-%d')"

      # Step 8: Upload Cypress Videos and Screenshots
      - name: Upload Cypress Videos and Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
